name = "ODMXMLTools"
uuid = "2456a17b-6ca2-4f51-9342-f0287e829718"
authors = ["PharmCat <v.s.arnautov@yandex.ru>"]
version = "0.1.0"

[deps]

DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[compat]

DataFrames = "1"
EzXML = "1.1"
julia = "1"

[extras]

Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]

test = ["Test"]
